<?php

namespace Database\Seeders\Backend\Setting;

use App\Models\Backend\Setting\Institute;
use Illuminate\Database\Seeder;

class InstituteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $institutes = [
            ['name' => 'Bangabandhu Sheikh Mujib Medical University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh Agricultural University,Mymensingh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh Open University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh University of Engineering & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh University of Professionals', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Chittagong University of Engineering & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Chittagong Veterinary and Animal Sciences University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Comilla University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Dhaka University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Dhaka University of Engineering & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Hajee Mohammad Danesh Science & Technology University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Islamic University, Kushtia ', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jagannath University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jahangirnagar University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jatiya Kabi Kazi Nazrul Islam University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jessore Science & Technology University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Khulna University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Khulna University of Engineering and Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Mawlana Bhashani Science & Technology University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'National University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Noakhali Science & Technology University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Pabna University of Science and Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Patuakhali Science And Technology University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Rajshahi University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Rajshahi University of Engineering & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Rangpur University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Shahjalal University of Science & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sher-e-Bangla Agricultural University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sylhet Agricultural University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University of Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Ahsanullah University of Science and Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'America Bangladesh University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'American International University Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'ASA University Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Asian University of Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Atish Dipankar University of Science & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh Islami University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh University of Business & Technology (BUBT)', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'BGC Trust University Bangladesh, Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'BRAC University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'City University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Daffodil International University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Darul Ihsan University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Dhaka International University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'East Delta University , Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'East West University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Eastern University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Gono Bishwabidyalay', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Green University of Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'IBAIS University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Independent University, Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'International Islamic University, Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'International University of Business Agriculture & Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Leading University, Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Manarat International University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Metropolitan University, Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'North South University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Northern University Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Premier University, Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Presidency University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Prime University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Primeasia University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Queens University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Royal University of Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Shanto Mariam University of Creative Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Southeast University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Southern University of Bangladesh , Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Stamford University, Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'State University Of Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sylhet International University, Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'The Millenium University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'The Peoples University of Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'The University of Asia Pacific', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'United International University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University of Development Alternative', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University of Information Technology & Sciences', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University of Liberal Arts Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University of Science & Technology, Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University of South Asia', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Uttara University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Victoria University of Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'World University of Bangladesh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Asian University for Women', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Islamic University of Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'South Asian University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Dhaka Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sir Salimullah Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Mymensingh Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Chittagong Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Rajshahi Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'MAG Osmani Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sher-E-Bangla Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Rangpur Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Comilla Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Khulna Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Shaheed Ziaur Rahman Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Dinajpur Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Faridpur Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Shaheed Suhrawardy Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Pabna Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Noakhali Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Cox`s Bazar Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jessore Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Shaheed Nazrul Islam Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Kushtia Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Satkhira Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sheikh Sayera Khatun Medical College, Gopalganj', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Feni Medical College,Feni', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Gono Bishwabidyalay, Savar, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Ad-din Womens Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Anwer Khan Modern Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Bangladesh Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jalalabad Rageb-Rabeya Medical College,Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'BGC Trust Medical College, Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Central Medical College, Comilla', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Chottagram Ma-O-Shishu Hospital Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Community Based Medical College (cbmc), Mymensingh', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Community Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Delta Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Dhaka National Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Durra Samad Rahman Red Crescent Women�s Medical College, Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Eastern Medical College, Comilla', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Enam Medical College, Savar, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sylhet Women`s Medical College, Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Green Life Medical College,Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Holy Family Red Crescent Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Ibrahim Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Ibn Sina Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'International Medical College, Gazipur', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Islami Bank Medical College, Rajshahi', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jahurul Islam Medical College, Kishoregonj', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Jalalabad Ragib-Rabeya Medical College Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Khawja Yunus Ali Medical College, Sirajganj', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Kumudini Medical College, Tangail', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Labaid Medical College[6] Dhanmondi, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Maulana Bhasani Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Medical College for Women and Hospital, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Nightingale Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'North Bengal Medical College, Sirajganj', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'North East Medical College, Sylhet', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Northern International Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Northern Private Medical College, Rangpur', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Popular Medical College & Hospital, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Prime Medical College, Rangpur', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Rangpur Community Hospital Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sahabuddin Medical College and Hospital', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Samaj Vittik Medical College, Mirzanagar, Savar', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Shahabuddin Medical College, Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Z. H. Sikder Women`s Medical College', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Southern Medical College, Chittagong', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Tairunnessa Memorial Medical College, Gazipur', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'TMSS Medical College,Bogra', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'University Of Science and Technology Chittagong. IAMS', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Uttara Adhunik Medical College,Dhaka', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Military Institute of Science and Technology (MIST)', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Others', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
            ['name' => 'Sonargaon University', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3'],
        ];

        foreach ($institutes as $institute) {
            Institute::create($institute);
        }
    }
}
